jobs:
  include:

  - name: test
    language: go
    install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - dep ensure -vendor-only
    script: ./scripts/test
    after_success: test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

  - name: deps
    language: python
    if: branch = master AND type = cron
    git:
      depth: false  # required for existing deps branches to be available
    install:
    - cd docs && scripts/install && cd ..
    - curl https://deps.app/install.sh | bash -s -- -b $HOME/bin
    script: deps ci
