#!/bin/sh -ex

echo "# JavaScript" > content/javascript.md
curl -s https://raw.githubusercontent.com/dropseed/deps-js/master/README.md?d=$(date +%s) | tail -n +2 >> content/javascript.md

echo "# Python" > content/python.md
curl -s https://raw.githubusercontent.com/dropseed/deps-python/master/README.md?d=$(date +%s) | tail -n +2 >> content/python.md

echo "# PHP" > content/php.md
curl -s https://raw.githubusercontent.com/dropseed/deps-php/master/README.md?d=$(date +%s) | tail -n +2 >> content/php.md

echo "# Git" > content/git.md
curl -s https://raw.githubusercontent.com/dropseed/deps-git/master/README.md?d=$(date +%s) | tail -n +2 >> content/git.md
