[build]
publish = "output"
command = "cd theme && ./scripts/install && cd .. && combine build"


[[redirects]]
    from = "/contact/"
    to = "/support/"

[[redirects]]
    from = "https://docs.dependencies.io/*"
    to = "https://www.dependencies.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/github-redirect/*"
    to = "https://github.com/:splat"
    status = 302

[[redirects]]
    from = "/apply/"
    to = "https://www.dropseed.dev/free/"

[[redirects]]
    from = "/travisci/"
    to = "/other-ci/"

[[redirects]]
    from = "/circleci/"
    to = "/other-ci/"

[[redirects]]
    from = "/github-actions/"
    to = "/github/"

[[redirects]]
    from = "/gitlab-ci/"
    to = "/gitlab/"

[[redirects]]
    from = "/bitbucket-pipelines/"
    to = "/bitbucket/"
