name: deps

on:
  schedule:
  - cron: 0 0 * * 1

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: cd docs && scripts/install && cd ..
    - run: curl https://deps.app/install.sh | bash -s -- -b $HOME/bin
    - run: $HOME/bin/deps ci
      env:
        DEPS_TOKEN: ${{ secrets.DEPS_TOKEN }}
        DEPS_GITHUB_APP_KEY: ${{ secrets.DEPS_GITHUB_APP_KEY }}
        DEPS_GITHUB_APP_ID: ${{ secrets.DEPS_GITHUB_APP_ID }}
        DEPS_GITHUB_APP_INSTALLATION_ID: ${{ secrets.DEPS_GITHUB_APP_INSTALLATION_ID }}
