on: [push]

jobs:
  workhorse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'
    - run: |
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure -vendor-only
    - run: ./scripts/test
