on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - uses: actions/checkout@v2
    - run: ./scripts/install
    - run: ./scripts/test
